### PR TITLE
Getting config settings from env variables in addition to app.yaml

### LINKED ISSUE #79: Implement configuration mechanism for non-App Engine use
Currently, the only way to pass configuration to the builder is via the runtime_config section of an app.yaml file that is within the directory that the builder is operating on.  This is only appropriate for App Engine deployments, therefore we need a more generic mechanism

### PR DESCRIPTION
**Pull request by ChengyuanZhao**
fixes #79

### CODE REVIEW

**Comment by meltsufin** [comment]
Looking at the README, I stared thinking how would I pass these commandline arguments to Cloud Build?
```
gcloud container builds submit /path/to/my/java/app \ 
    --config java.yaml \
    --substitutions _OUTPUT_IMAGE=$OUTPUT_IMAGE
```

Also, it seems quiet annoying to have to specify all the `*-map` and `*-image` arguments for local runs. Can we somehow read them from `java.yaml`, if they're not provided as command-line args?
This may be for another PR, but the whole goal of allowing the builder to be used as a standalone tool seems incomplete without it.

@balopat FYI

**Comment by ChengyuanZhao** [comment]
@meltsufin would it make sense to make a separate issue and pr for that? The issue we have linked in the description only mentions replacing app.yaml settings

**Comment by meltsufin** [comment]
@ChengyuanZhao I think there are two issues here. 

1. How would I pass these commandline arguments to Cloud Build?
2. Have defaults for `*-map` and `*-image` arguments for local runs.

Which one, or both, do you want to handle in a separate PR?

**Comment by ChengyuanZhao** [comment]
@meltsufin 

regarding:

1. for this point you mean these arguments I added in this PR? I included a few sentences in the readme that tell the user they can add these command line args in the java.yaml file.  By Cloud Build you mean this command right? 

# initiate the cloud container build
gcloud container builds submit /path/to/my/java/app \ 
    --config java.yaml \
    --substitutions _OUTPUT_IMAGE=$OUTPUT_IMAGE


2. This one is the one I wanted to do in a separate PR.

**Comment by meltsufin** [comment]
1. I see. So, one would need to edit the `java.yaml`. Let's leave it that way for now.

2. Please create an issue for that. Thanks!

**Comment by meltsufin** [comment]
#87 created for (2).

**Pull request merged**
